openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
servers:
  - url: http://your.server.name
paths:
  /user:
    put:
      summary: Updates a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      summary: Deletes a user
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
  /{route}:
    parameters:
      - name: route
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Dynamic route
      responses:
        '200':
          description: Successful operation
        '404':
          description: Not found
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string